---
title             : "Toddlers' Comprehension of Negation (Registered Report)"
shorttitle        : "Toddlers' Comprehension of Negation (Registered Report)"

author: 
  - name          : "Masoud Jasbi"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "masoud_jasbi@fas.harvard.edu"
  - name          : "Annika McDermott-Hinman"
    affiliation   : "1,2"

affiliation:
  - id            : "1"
    institution   : "Harvard University"
  - id            : "2"
    institution   : "Brown University"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.One sentence clearly stating the **general problem** being addressed by  this particular study. One sentence summarizing the main result (with the words "**here we show**" or their equivalent).Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.One or two sentences to put the results into a more **general context**. Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.

keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

# Introduction

# Methods


## Participants

## Material

## Procedure

## Data analysis

```{r import_data}
processed_data <- read.csv("data/processed_data/processed_data.csv")
```

```{r preparation}
summary_data <-
  processed_data %>%
  filter(trialType=="Still") %>%
  group_by(trial_type) %>%
  summarize(mean_lookingTime = mean(looking_time))
```

```{r lookingTimePlot}
summary_data %>%
  ggplot(aes(trial_type,mean_lookingTime)) +
  geom_bar(stat = "identity") +
  xlab("Mean Looking Time") + ylab("Trial Types") +
  theme_classic()
```

# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "bibliography.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
